### ISSUE TITLE
Dummy Data Missing

### ISSUE THREAD

**Issue by ddsouzapq1** [paypal/Iguanas#18]
Hello! I think the tutorial will be much easier to follow and play along if the dummy data( that is being used in the examples) is provided. Is there a place that I can get that from? :)  Thank you!

**Comment by lamesjaidler** [comment]
@ddsouzapq1 sorry about the delay, I didn't get a notification for this. I will add the dummy data as soon as I can!

**Comment by lamesjaidler** [comment]
@ddsouzapq1  I see dummy data in most of the folders - can you specify where the data is missing please?

**Comment by ddsouzapq1** [comment]
My bad James. I couldn't find it in the upper level folders. I don't know if adding a line to the documentation pointing to the exact location of the files will be useful, but I will close this issue. Thanks again! :)
